### ISSUE TITLE
Filter, Add to cart, categories

### ISSUE THREAD

**Issue by chikakow** [aviabird/angularspree#74]
Hi,
First of all, thank you for all your contributions! There are lots of great examples to learn patterns from!
But looks like Filter, Add to cart, categories are not working.  Are you guys still actively working on this project?

**Comment by kartikjagdale** [comment]
hi @chikakow thanks for raising this issue.
its working now, you can check the website.
We figured out the issue is caused because of this bug: https://github.com/aviabird/angularspree/issues/57
the databse limit gets full as the api is hosted on heroku. we need to reset the db timely in order to make things right again.
If you got some time feel free to resolve this issue https://github.com/aviabird/angularspree/issues/57 and send a PR. 
Thank you !
